## CSV CLEANING

Come with us to see the cleaning process we followed with a dataset about employee attrition.

In [2]:
import pandas as pd

df = pd.read_csv("./HR-Employee-Attrition.csv")

In [2]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

We didn't examine a lot the dataset for several reasons:
1. We wanted to do as much as we could in MySQL
2. The dataset is from Kaggle and we examined it there

We use the data card from Kaggle and the columns description to understand each column. Later, we decided what columns were relevant for our analysis and which ones we should drop.

In [4]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [3]:
df = df.drop(columns = ['DailyRate', 'Education', 'EducationField', 'EmployeeCount', 'Gender', 'HourlyRate',
       'JobLevel', 'MaritalStatus', 'MonthlyRate', 'Over18', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears'])

In [4]:
df.shape

(1470, 19)

We started with 35 columns and left only 19. We saved the new dataset in a csv file. This dataset is going to be the dataset that we'll use in the project.

In [6]:
df.to_csv("./ibm_data.csv", index = False)

In [3]:
df = pd.read_csv("./ibm_data.csv")

In [4]:
df

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,EmployeeNumber,EnvironmentSatisfaction,JobInvolvement,JobRole,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,1,2,3,Sales Executive,4,5993,8,Yes,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,2,3,2,Research Scientist,2,5130,1,No,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,4,4,2,Laboratory Technician,3,2090,6,Yes,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,5,4,3,Research Scientist,3,2909,1,Yes,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,7,1,3,Laboratory Technician,2,3468,9,No,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,Research & Development,23,2061,3,4,Laboratory Technician,4,2571,4,No,3,3,5,2,0,3
1466,39,No,Travel_Rarely,Research & Development,6,2062,4,2,Healthcare Representative,1,9991,4,No,5,3,7,7,1,7
1467,27,No,Travel_Rarely,Research & Development,4,2064,2,4,Manufacturing Director,2,6142,1,Yes,0,3,6,2,0,3
1468,49,No,Travel_Frequently,Sales,2,2065,4,2,Sales Executive,2,5390,2,No,3,2,9,6,0,8
1469,34,No,Travel_Rarely,Research & Development,8,2068,2,4,Laboratory Technician,3,4404,2,No,3,4,4,3,1,2